
export default [
    {
        title: "Dashboard",
        route: "agent-dashboard",
        icon: "GridIcon",
        action: "all", 
        resource: "agent",
        icon2DLight: require("@/assets/images/light-icons-fav/dashboard.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/dashboard.png"),
        icon3D: require("@/assets/images/fill-icon/dashboard.png"),
    },
    {
        title: "On Boarding",
        route: 'agent-onboarding',
        icon: "MapIcon",
        action: "all",
        resource: "agent",
        icon2DLight: require("@/assets/images/light-icons-fav/onboarding.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/onboarding.png"),
        icon3D: require("@/assets/images/fill-icon/onboarding.png"),
    },
    {
        title: "Offer Wall",
        route: 'offer-wall',
        icon: "GridIcon",
        action: "all",
        resource: "agent",
        icon2DLight: require("@/assets/images/light-icons-fav/offerwall.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/offerwall.png"),
        icon3D: require("@/assets/images/fill-icon/offerwall.png"),
    },

    {
        title: "Contact Center",
        route: "contact-center",
        icon: "PhoneIcon",
        action: "all",
        resource: "agent",
        icon2DLight: require("@/assets/images/light-icons-fav/dashboard.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/dashboard.png"),
        icon3D: require("@/assets/images/fill-icon/dashboard.png"),
    },
    {
        title: "Contact User",
        route: "user-contact-center",
        icon: "UserIcon",
        action: "all",
        resource: "agent",
        icon2DLight: require("@/assets/images/light-icons-fav/cont-user.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/cont-user.png"),
        icon3D: require("@/assets/images/fill-icon/cont-user.png"),
    },
    {
        title: "University",
        route: "university",
        icon: "AwardIcon",
        action: "all",
        resource: "agent",
        icon2DLight: require("@/assets/images/light-icons-fav/university.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/university.png"),
        icon3D: require("@/assets/images/fill-icon/university.png"),

    },
    {
        title: "Purchased History",
        route: "course-invoice",
        icon: "ClockIcon",
        action: "all",
        resource: "agent",
        // icon2DLight: require("@/assets/images/light-icons-fav/university.png"),
        // icon2DDark: require("@/assets/images/dark-icons-fav/university.png"),
        // icon3D: require("@/assets/images/fill-icon/university.png"),

    },
    {
        title: "Activity",
        route: "agent-activity",
        icon: "ActivityIcon",
        action: 'all',
        resource: 'agent',
        icon2DLight: require("@/assets/images/light-icons-fav/activity.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/activity.png"),
        icon3D: require("@/assets/images/fill-icon/activity.png"),
    },
    {
        title: "Wallet",
        route: "wallet",
        icon: "BookOpenIcon",
        action: "all",
        resource: "agent",
        icon2DLight: require("@/assets/images/light-icons-fav/wallet.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/wallet.png"),
        icon3D: require("@/assets/images/fill-icon/wallet.png"),
    },
    {
        title: "Contract",
        icon: "GridIcon",
        icon2DLight: require("@/assets/images/light-icons-fav/dashboard.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/dashboard.png"),
        icon3D: require("@/assets/images/fill-icon/dashboard.png"),
        children: [
            {
                title: "Inbox",
                route: "inbox",
                action: "all",
                resource: "agent",
                icon: "CircleIcon",
                icon2DLight: require("@/assets/images/light-icons-fav/dashboard.png"),
                icon2DDark: require("@/assets/images/dark-icons-fav/dashboard.png"),
                icon3D: require("@/assets/images/fill-icon/dashboard.png"),
            },
        ],
    },
    {
        title: "Security",
        route: "agent-security",
        icon: "ShieldIcon",
        action: 'all',
        resource: 'agent',
        icon2DLight: require("@/assets/images/light-icons-fav/shield.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/shield.png"),
        icon3D: require("@/assets/images/fill-icon/shield.png"),
    },
    {
        title: "Schedules",
        route: "agent-schedules",
        icon: "CalendarIcon",
        action: 'all',
        resource: 'agent',
        icon2DLight: require("@/assets/images/light-icons-fav/dashboard.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/dashboard.png"),
        icon3D: require("@/assets/images/fill-icon/dashboard.png"),
    },
    {
        title: "Payouts",
        route: "agent-payout-settings",
        icon: "CreditCardIcon",
        action: 'all',
        resource: 'agent',
        icon2DLight: require("@/assets/images/light-icons-fav/payout.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/payout.png"),
        icon3D: require("@/assets/images/fill-icon/payout.png"),
    },

    {
        title: "Setting",
        // route: 'staff-management',
        icon: "SettingsIcon",
        icon2DLight: require("@/assets/images/light-icons-fav/setting.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/setting.svg"),
        icon3D: require("@/assets/images/fill-icon/setting.png"),
        children: [
            {
                title: "Account Setting",
                route: "account-setting",
                action: "all",
                resource: "agent",
                icon: "CircleIcon",
                icon2DLight: require("@/assets/images/light-icons-fav/subject.svg"),
                icon2DDark: require("@/assets/images/dark-icons-fav/subject.svg"),
                icon3D: require("@/assets/images/fill-icon/subject.svg"),
            },
            // {
            //     title: "Payout Setting",
            //     route: 'agent-payout-settings',
            //     action: "all",
            //     resource: "agent",
                    // icon2DLight: require("@/assets/images/light-icons-fav/dashboard.png"),
                    // icon2DDark: require("@/assets/images/dark-icons-fav/dashboard.png"),
                    // icon3D: require("@/assets/images/fill-icon/dashboard.png"),
            // },
        ],
    },
];
