export default [
  {
    title: "Dashboard",
    route: "client-dashboard",
    icon: "GridIcon",
    action: "all",
    resource: "client",
    icon2DLight: require("@/assets/images/light-icons-fav/dashboard.png"),
    icon2DDark: require("@/assets/images/dark-icons-fav/dashboard.png"),
    icon3D: require("@/assets/images/fill-icon/dashboard.png"),
  },
  {
    title: "LMS",
    icon: "LayersIcon",
    action: "all",
    resource: "client",
    icon2DLight: require("@/assets/images/light-icons-fav/open book.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/lms.svg"),
    icon3D: require("@/assets/images/fill-icon/book.png"),
    children: [
      {
        title: "Create Course",
        icon: "CircleIcon",
        action: "all",
        resource: "client",
        route: "create-course",
        icon2DLight: require("@/assets/images/light-icons-fav/book-add.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/create-course.svg"),
        icon3D: require("@/assets/images/fill-icon/book-add.png"),
      },
      {
        title: "View Course",
        icon: "CircleIcon",
        action: "all",
        resource: "client",
        route: "list-course",
        icon2DLight: require("@/assets/images/light-icons-fav/book-minus.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/course-view.svg"),
        icon3D: require("@/assets/images/fill-icon/book-check.png"),
      },
      {
        title: "Drafted Course",
        icon: "CircleIcon",
        action: "all",
        resource: "client",
        route: "drafted-course",
        icon2DLight: require("@/assets/images/light-icons-fav/book-minus.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/course-view.svg"),
        icon3D: require("@/assets/images/fill-icon/book-check.png"),
      },
    ],
  },

  {
    title: "Reporting",
    icon: "ActivityIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/list view-circle.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/human-resource.svg"),
    icon3D: require("@/assets/images/fill-icon/list view-circle.png"),
    children: [
      {
        title: "Summary",
        route: "client-reporting-performance",
        action: "all",
        resource: "client",
        icon: "CircleIcon",
        icon2DLight: require("@/assets/images/light-icons-fav/back-office.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/back-office.svg"),
        icon3D: require("@/assets/images/fill-icon/layout 11.png"),
      },
      {
        title: "TimeLine",
        route: "client-reporting-timeline",
        action: "all",
        resource: "client",
        icon: "CircleIcon",
        icon2DLight: require("@/assets/images/light-icons-fav/front-office.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/front-office.svg"),
        icon3D: require("@/assets/images/fill-icon/layout 12.png"),
      },
      {
        title: "Saved Reports",
        icon: "ActivityIcon",
        action: "all",
        resource: "client",
        icon: "CircleIcon",
        icon2DLight: require("@/assets/images/light-icons-fav/list view-circle.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/human-resource.svg"),
        icon3D: require("@/assets/images/fill-icon/list view-circle.png"),
        children: [
          {
            title: "",
            action: "all",
            resource: "client",
          }

          ]
      },
    ],
  },

  {
    title: "Campaign on Boarding",
    route: "services-required",
    icon: "UserIcon",
    resource: "client",
    action: "all",
    resource: "client",
    icon2DLight: require("@/assets/images/light-icons-fav/onboarding.png"),
    icon2DDark: require("@/assets/images/dark-icons-fav/onboarding.png"),
    icon3D: require("@/assets/images/fill-icon/onboarding.png"),
  },
  {
    title: "Offer Wall",
    route: "offer-wall",
    icon: "GridIcon",
    action: "all",
    resource: "client",
    icon2DLight: require("@/assets/images/light-icons-fav/offerwall.png"),
    icon2DDark: require("@/assets/images/dark-icons-fav/offerwall.png"),
    icon3D: require("@/assets/images/fill-icon/offerwall.png"),
  },
  {
    title: "Activity",
    route: "client-activity",
    icon: "ActivityIcon",
    action: "all",
    resource: "client",
    icon2DLight: require("@/assets/images/light-icons-fav/activity.png"),
    icon2DDark: require("@/assets/images/dark-icons-fav/activity.png"),
    icon3D: require("@/assets/images/fill-icon/activity.png"),
  },
  {
    title: "University",
    route: "university",
    icon: "AwardIcon",
    action: "all",
    resource: "client",
    icon2DLight: require("@/assets/images/light-icons-fav/university.png"),
    icon2DDark: require("@/assets/images/dark-icons-fav/university.png"),
    icon3D: require("@/assets/images/fill-icon/university.png"),
  },
  {
    title: "Purchased History",
    route: "course-invoice",
    icon: "ClockIcon",
    action: "all",
    resource: "client",
    // icon2DLight: require("@/assets/images/light-icons-fav/university.png"),
    // icon2DDark: require("@/assets/images/dark-icons-fav/university.png"),
    // icon3D: require("@/assets/images/fill-icon/university.png"),
  },
  {
    title: "Security",
    route: "client-security",
    icon: "ShieldIcon",
    action: "all",
    resource: "client",
    icon2DLight: require("@/assets/images/light-icons-fav/shield.png"),
    icon2DDark: require("@/assets/images/dark-icons-fav/shield.png"),
    icon3D: require("@/assets/images/fill-icon/shield.png"),
  },
  {
      title: "Wallet",
      route: "wallet",
      icon: "GridIcon",
      action: 'all',
      resource: 'client',
      icon2DLight: require("@/assets/images/light-icons-fav/wallet.png"),
      icon2DDark: require("@/assets/images/dark-icons-fav/wallet.png"),
      icon3D: require("@/assets/images/fill-icon/wallet.png"),
  },

  // {
  //   title: "Wallet",
  //   icon: "GridIcon",
  //   icon2DLight: require("@/assets/images/light-icons-fav/wallet.png"),
  //   icon2DDark: require("@/assets/images/dark-icons-fav/wallet.png"),
  //   icon3D: require("@/assets/images/fill-icon/wallet.png"),
  //   children: [
  //     {
  //       title: "Wallet",
  //       route: "wallet",
  //       action: "all",
  //       resource: "client",
  //       icon2DLight: require("@/assets/images/light-icons-fav/wallet.png"),
  //       icon2DDark: require("@/assets/images/dark-icons-fav/wallet.png"),
  //       icon3D: require("@/assets/images/fill-icon/wallet.png"),
  //     },
  //     {
  //       title: "Invoices Detail",
  //       route: "invoices-detail",
  //       action: "all",
  //       resource: "client",
  //       icon2DLight: require("@/assets/images/light-icons-fav/wallet.png"),
  //       icon2DDark: require("@/assets/images/dark-icons-fav/wallet.png"),
  //       icon3D: require("@/assets/images/fill-icon/wallet.png"),
  //     },
  //   ],
  // },
  {
    title: "Setting",
    // route: 'staff-management',
    icon: "SettingsIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/setting.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/setting.svg"),
    icon3D: require("@/assets/images/fill-icon/setting.png"),
    children: [
      {
        title: "Account Setting",
        route: "client-account-setting",
        action: "all",
        resource: "client",
        icon: "CircleIcon",
        icon2DLight: require("@/assets/images/light-icons-fav/subject.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/subject.svg"),
        icon3D: require("@/assets/images/fill-icon/subject.svg"),
      },
    ],
  },
];
