
export default [
    {
        title: "Dashboard",
        route: "publisher-dashboard",
        icon: "GridIcon",
        action: "all",
        resource: "publisher",
        icon2DLight: require("@/assets/images/light-icons-fav/dashboard.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/dashboard.png"),
        icon3D: require("@/assets/images/fill-icon/dashboard.png"),
    },
    {
        title: "Offer Wall",
        route: 'offer-wall',
        icon: "GridIcon",
        action: "all",
        resource: "publisher",
        icon2DLight: require("@/assets/images/light-icons-fav/offerwall.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/offerwall.png"),
        icon3D: require("@/assets/images/fill-icon/offerwall.png"),
    },
    {
        title: "Reporting",
        icon: "ActivityIcon",
        icon2DLight: require("@/assets/images/light-icons-fav/list view-circle.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/human-resource.svg"),
        icon3D: require("@/assets/images/fill-icon/list view-circle.png"),
        children: [
            {
                title: "Summary",
                route: "publisher-reporting-performance",
                action: "all",
                resource: "publisher",
                icon: "CircleIcon",
                icon2DLight: require("@/assets/images/light-icons-fav/back-office.svg"),
                icon2DDark: require("@/assets/images/dark-icons-fav/back-office.svg"),
                icon3D: require("@/assets/images/fill-icon/layout 11.png"),
            },
            {
                title: "TimeLine",
                route: "publisher-reporting-timeline",
                action: "all",
                resource: "publisher",
                icon: "CircleIcon",
                icon2DLight: require("@/assets/images/light-icons-fav/front-office.svg"),
                icon2DDark: require("@/assets/images/dark-icons-fav/front-office.svg"),
               icon3D: require("@/assets/images/fill-icon/layout 12.png"),
            },
            {
                title: "Saved Reports",
                icon: "ActivityIcon",
                action: "all",
                resource: "publisher",
                icon: "CircleIcon",
                icon2DLight: require("@/assets/images/light-icons-fav/list view-circle.svg"),
                icon2DDark: require("@/assets/images/dark-icons-fav/human-resource.svg"),
                icon3D: require("@/assets/images/fill-icon/list view-circle.png"),
                children: [
                  {
                    title: "",
                    action: "all",
                    resource: "publisher",
                  }
                  ]
              },
        ],
    },
    {
        title: "Activity",
        route: "publisher-activity",
        icon: "ActivityIcon",
        action: 'all',
        resource: 'publisher',
        icon2DLight: require("@/assets/images/light-icons-fav/activity.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/activity.png"),
        icon3D: require("@/assets/images/fill-icon/activity.png"),
    },
    {
        title: "Wallet",
        route: "wallet",
        icon: "GridIcon",
        action: 'all',
        resource: 'publisher',
        icon2DLight: require("@/assets/images/light-icons-fav/wallet.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/wallet.png"),
        icon3D: require("@/assets/images/fill-icon/wallet.png"),
    },
    {
        title: "University",
        route: "university",
        icon: "AwardIcon",
        action: "all",
        resource: "publisher",
        icon2DLight: require("@/assets/images/light-icons-fav/university.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/university.png"),
        icon3D: require("@/assets/images/fill-icon/university.png"),

    },
    {
        title: "Purchased History",
        route: "course-invoice",
        icon: "ClockIcon",
        action: "all",
        resource: "publisher",
        // icon2DLight: require("@/assets/images/light-icons-fav/university.png"),
        // icon2DDark: require("@/assets/images/dark-icons-fav/university.png"),
        // icon3D: require("@/assets/images/fill-icon/university.png"),

    },

    {
        title: "Security",
        route: "publisher-security",
        icon: "ShieldIcon",
        action: 'all',
        resource: 'publisher',
        icon2DLight: require("@/assets/images/light-icons-fav/shield.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/shield.png"),
        icon3D: require("@/assets/images/fill-icon/shield.png"),
    },

    {
        title: "Publisher Onboarding",
        route: "publisher-onbaording-index",
        icon: "ActivityIcon",
        action: 'all',
        resource: 'publisher',
        icon2DLight: require("@/assets/images/light-icons-fav/onboarding.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/onboarding.png"),
        icon3D: require("@/assets/images/fill-icon/onboarding.png"),
    },
    {
        title: "Manage Number",
        route: "manage-number",
        icon: "ActivityIcon",
        action: 'all',
        resource: 'publisher',
        icon2DLight: require("@/assets/images/light-icons-fav/onboarding.png"),
        icon2DDark: require("@/assets/images/dark-icons-fav/onboarding.png"),
        icon3D: require("@/assets/images/fill-icon/onboarding.png"),
    },

    {
        title: "Setting",
        icon: "SettingsIcon",
        icon2DLight: require("@/assets/images/light-icons-fav/setting.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/setting.svg"),
        icon3D: require("@/assets/images/fill-icon/setting.png"),
        children: [
            {
                title: "Account Setting",
                route: "account-setting",
                action: "all",
                resource: "publisher",
                icon: "CircleIcon",
                icon2DLight: require("@/assets/images/light-icons-fav/subject.svg"),
                icon2DDark: require("@/assets/images/dark-icons-fav/subject.svg"),
                icon3D: require("@/assets/images/fill-icon/subject.svg"),
            },
            {
                title: "Payout Setting",
                route: "publisher-payout-setting",
                action: "all",
                resource: "publisher",
                icon: "CircleIcon",
                icon2DLight: require("@/assets/images/light-icons-fav/filter 7.svg"),
                icon2DDark: require("@/assets/images/dark-icons-fav/filter 7.svg"),
                icon3D: require("@/assets/images/fill-icon/filter 7.svg")
            },
        ],
    },
];
