export default [
  {
    title: "Dashboard",
    route: "admin-dashboard",
    icon: "GridIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/dashboard.png"),
    icon2DDark: require("@/assets/images/dark-icons-fav/dashboard.png"),
    icon3D: require("@/assets/images/fill-icon/dashboard.png"),
  },
  {
    title: "User Management",
    route: "admin-user-management",
    icon: "UserIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/user.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/user.svg"),
    icon3D: require("@/assets/images/fill-icon/User.png"),
  },
  {
    title: "Staff Management",
    // route: 'staff-management',
    icon: "ActivityIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/users 3.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/users 3.svg"),
    icon3D: require("@/assets/images/fill-icon/users 3.png"),
    children: [
      {
        title: "Front Office",
        icon: "CircleIcon",
        route: "staff-management-front-office",
        icon2DLight: require("@/assets/images/light-icons-fav/front-office.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/front-office.svg"),
        icon3D: require("@/assets/images/fill-icon/layout 12.png"),
      },
      {
        title: "Middle Office",
        icon: "CircleIcon",
        route: "staff-management-middle-office",
        icon2DLight: require("@/assets/images/light-icons-fav/back-office.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/back-office.svg"),
        icon3D: require("@/assets/images/fill-icon/layout 11.png"),
      },
      {
        title: "Back Office",
        icon: "CircleIcon",
        route: "staff-management-back-office",
        icon2DLight: require("@/assets/images/light-icons-fav/middle-office.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/middle-office.svg"),
        icon3D: require("@/assets/images/fill-icon/layout 13.png"),
      },
    ],
    // action: 'all',
    // resource: 'client',
  },
  {
    title: "Reporting",
    icon: "ActivityIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/list view-circle.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/human-resource.svg"),
    icon3D: require("@/assets/images/fill-icon/list view-circle.png"),
   children: [
    {
      title: "Summary",
      icon: "CircleIcon",
      route: "reporting-performance",
      icon2DLight: require("@/assets/images/light-icons-fav/back-office.svg"),
      icon2DDark: require("@/assets/images/dark-icons-fav/back-office.svg"),
      icon3D: require("@/assets/images/fill-icon/layout 11.png"),
    },
      {
        title: "TimeLine",
        icon: "CircleIcon",
        route: "reporting-timeline",
        icon2DLight: require("@/assets/images/light-icons-fav/front-office.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/front-office.svg"),
        icon3D: require("@/assets/images/fill-icon/layout 12.png"),

      },
      {
        title: "Saved Reports",
        icon: "ActivityIcon",
        icon2DLight: require("@/assets/images/light-icons-fav/list view-circle.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/human-resource.svg"),
        icon3D: require("@/assets/images/fill-icon/list view-circle.png"),
        children: [
          {
            title: "",
          }

          ]
      },


    ],
    // action: 'all',
    // resource: 'client',
  },
  {
    title: "LMS",
    icon: "LayersIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/open book.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/lms.svg"),
    icon3D: require("@/assets/images/fill-icon/book.png"),
    children: [
      {
        title: "Create Course",
        icon: "CircleIcon",
        route: "create-course",
        icon2DLight: require("@/assets/images/light-icons-fav/book-add.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/create-course.svg"),
        icon3D: require("@/assets/images/fill-icon/book-add.png"),
      },
      {
        title: "Course List",
        icon: "CircleIcon",
        route: "list-course",
        icon2DLight: require("@/assets/images/light-icons-fav/book-minus.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/course-view.svg"),
        icon3D: require("@/assets/images/fill-icon/book-check.png"),
      },
      {
        title: "Drafted Course",
        icon: "CircleIcon",
        route: "drafted-course",
        icon2DLight: require("@/assets/images/light-icons-fav/book-minus.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/course-view.svg"),
        icon3D: require("@/assets/images/fill-icon/book-check.png"),
      },
    ],
  },
  {
    title: "Campaign",
    icon: "ArchiveIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/announcement.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/campaign.svg"),
    icon3D: require("@/assets/images/fill-icon/announcement.png"),

    children: [
      {
        title: "Create Campaign",
        icon: "CircleIcon",
        route: "campaign-creation",
        icon2DLight: require("@/assets/images/light-icons-fav/new-camp.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/new-camp.svg"),
        icon3D: require("@/assets/images/fill-icon/new-camp.png"),
      },
      {
        title: "Complete Campaign",
        icon: "CircleIcon",
        route: "campaign-list-complete",
        icon2DLight: require("@/assets/images/light-icons-fav/all-camp.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/all-camp.svg"),
        icon3D: require("@/assets/images/fill-icon/all-camp.png"),
      },
      {
        title: "Draft Campaign",
        icon: "CircleIcon",
        route: "campaign-list-draft",
        icon2DLight: require("@/assets/images/light-icons-fav/draft-camp.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/draft-camp.svg"),
        icon3D: require("@/assets/images/fill-icon/draft-camp.png"),
      },
    ],
  },
  {
    title: "Offer Wall",
    route: "offer-wall",
    icon: "GridIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/bar chart.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/financials.svg"),
    icon3D: require("@/assets/images/fill-icon/bar chart.png"),
  },
  {
    title: "IVR",
    icon: "LayersIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/line chart.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/ivr.svg"),
    icon3D: require("@/assets/images/fill-icon/line chart.png"),
    children: [
      {
        title: "Create IVR Tree",
        icon: "CircleIcon",
        route: "ivr-creation",
        icon2DLight: require("@/assets/images/light-icons-fav/line chart 3.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/create-ivr.svg"),
        icon3D: require("@/assets/images/fill-icon/line chart 2.png"),
      },
      {
        title: "Manage IVR",
        icon: "CircleIcon",
        route: "ivr-manage",
        icon2DLight: require("@/assets/images/light-icons-fav/cube stack.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/manage-ivr.svg"),
        icon3D: require("@/assets/images/fill-icon/cube stack.png"),
      },
      {
        title: "Routing Plans",
        icon: "CircleIcon",
        route: "routings",
        icon2DLight: require("@/assets/images/light-icons-fav/cube stack.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/manage-ivr.svg"),
        icon3D: require("@/assets/images/fill-icon/cube stack.png"),
      },
    ],
  },
  {
    title: "Numbers",
    icon: "PhoneIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/line chart.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/ivr.svg"),
    icon3D: require("@/assets/images/fill-icon/line chart.png"),
    children: [
      {
        title: "Manage Number",
        icon: "CircleIcon",
        route: "manage-number",
        icon2DLight: require("@/assets/images/light-icons-fav/line chart 3.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/create-ivr.svg"),
        icon3D: require("@/assets/images/fill-icon/line chart 2.png"),
      },
    ],
  },
  {
    title: "Contract",
    icon: "LayersIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/open book.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/lms.svg"),
    icon3D: require("@/assets/images/fill-icon/book.png"),
    children: [
      {
        title: "Create Contract",
        icon: "CircleIcon",
        route: "create-contract",
        icon2DLight: require("@/assets/images/light-icons-fav/book-add.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/create-course.svg"),
        icon3D: require("@/assets/images/fill-icon/book-add.png"),
      },
      {
        title: "Create Template",
        icon: "CircleIcon",
        route: "create-template",
        icon2DLight: require("@/assets/images/light-icons-fav/book-minus.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/course-view.svg"),
        icon3D: require("@/assets/images/fill-icon/book-check.png"),
      },
      {
        title: "Template",
        icon: "CircleIcon",
        route: "template",
        icon2DLight: require("@/assets/images/light-icons-fav/book-minus.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/course-view.svg"),
        icon3D: require("@/assets/images/fill-icon/book-check.png"),
      },
    ],
  },
  {
    title: "Financials",
    route: "financials",
    icon: "GridIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/bar chart.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/financials.svg"),
    icon3D: require("@/assets/images/fill-icon/bar chart.png"),
  },
  {
    title: "Accounting",
    route: "accounting",
    icon: "ArchiveIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/zoom-text.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/accounting.svg"),
    icon3D: require("@/assets/images/fill-icon/zoom-text.png"),
  },
  // {
  //   title: "Human Resources",
  //   route: 'human-resources',
  //   icon: "UsersIcon",
  //   icon2DLight: require("@/assets/images/light-icons-fav/list view-circle.svg"),
  //   icon2DDark: require("@/assets/images/dark-icons-fav/human-resource.svg"),
  //   icon3D: require("@/assets/images/fill-icon/list view-circle.png"),
  // },
  {
    title: "Api Documentaion",
    route: "api-documentation",
    icon: "ArchiveIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/list view-circle.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/human-resource.svg"),
    icon3D: require("@/assets/images/fill-icon/list view-circle.png"),
  },

  {
    title: "Settings",
    icon: "SettingsIcon",
    icon2DLight: require("@/assets/images/light-icons-fav/setting.svg"),
    icon2DDark: require("@/assets/images/dark-icons-fav/setting.svg"),
    icon3D: require("@/assets/images/fill-icon/setting.png"),
    children: [
      {
        title: "System Settings",
        icon: "CircleIcon",
        route: "settings-system",
        icon2DLight: require("@/assets/images/light-icons-fav/sort-circle.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/sort-circle.svg"),
        icon3D: require("@/assets/images/fill-icon/sort-circle.svg"),
      },
      {
        title: "Services",
        icon: "CircleIcon",
        route: "settings-services",
        icon2DLight: require("@/assets/images/light-icons-fav/subject.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/subject.svg"),
        icon3D: require("@/assets/images/fill-icon/subject.svg"),
      },
      {
        title: "Dropdown",
        icon: "CircleIcon",
        route: "settings-dropdown",
        icon2DLight: require("@/assets/images/light-icons-fav/filter 7.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/filter 7.svg"),
        icon3D: require("@/assets/images/fill-icon/filter 7.svg"),
      },
      {
        title: "Type",
        icon: "CircleIcon",
        route: "settings-type",
        icon2DLight: require("@/assets/images/light-icons-fav/subject.svg"),
        icon2DDark: require("@/assets/images/dark-icons-fav/subject.svg"),
        icon3D: require("@/assets/images/fill-icon/subject.svg"),
      },
    ],
  },
  // {
  //   title: "Logout",
  //   icon: "LogOutIcon",
  // },
];
